ingredients = {'alit hide': ['drain intelligence', 'resist poison', 'telekinesis','detect animal'],
'ampoule pod': ['water walking', 'paralyze','detect animal', 'drain willpower'],
'ash salts': ['drain agility', 'resist magicka', 'cure blight disease' 'resist magicka'],
'ash yam': ['fortify intelligence', 'fortify strength', 'resist common disease', 'detect key'],
'bittergreen petal': ['restore intelligence', 'invisibility', 'drain endurance', 'drain magicka'],
'black anther': ['drain agility', 'resist fire', 'drain endurance', 'light'],
'black lichen': ['drain strength', 'resist frost', 'drain speed', 'cure poison'],
'bloat': ['drain magicka','fortify intelligence','fortify willpower','detect animal'],
'bonemeal': ['restore agility', 'telekinesis', 'drain fatigue', 'drain personality'],
'bread': ['restore fatigue'],
"bungler's bane": ['drain speed', 'drain endurance', 'dispel', 'drain strength'],
'chokeweed': ['drain luck', 'restore fatigue', 'cure common disease', 'drain willpower'],
'coda flower': ['drain personality', 'levitate', 'drain intelligence', 'drain health'],
'comberry': ['drain fatigue', 'restore magicka', 'fire shield', 'reflect'],
'corkbulb root': ['cure paralyzation', 'restore health', 'lightning shield', 'fortify luck'],
'corprus weepings': ['drain fatigue', 'fortify luck', 'drain willpower', 'restore health'],
'crab meat': ['restore fatigue','resist shock','lightning shield','restore luck'],
'daedra skin': ['fortify strength','cure common disease','paralyze','swift swim'],
"daedra's heart": ['restore magicka','fortify endurance','drain agility','night eye'],
'diamond': ['drain agility','invisibility','reflect','detect key'],
'dreugh wax': ['fortify strength','restore strength','drain luck','drain willpower'],
'ectoplasm': ['fortify agility','detect animal','drain strength','drain health'],
'emerald': ['fortify magicka','restore health','drain agility','drain endurance'],
'fire petal': ['resist fire','drain health','spell absorption','paralyze'],
'fire salts': ['drain health','fortify agility','resist frost','fire shield'],
'frost salts': ['drain speed','restore magicka','frost shield','resist fire'],
'ghoul heart': ['paralyze','cure poison','fortify attack'],
'gold kanet': ['drain health','burden','drain luck','restore strength'],
'gravedust': ['drain intelligence','cure common disease','drain magicka','restore endurance'],
'green lichen': ['fortify personality','cure common disease','drain strength','drain health'],
'guar hide': ['drain fatigue','fortify endurance','restore personality','fortify luck'],
'hackle-lo leaf': ['restore fatigue','paralyze','water breathing','restore luck'],
'heather': ['restore personality','feather','drain speed','drain personality'],
'hound meat': ['restore fatigue','fortify fatigue','reflect','detect enchantment'],
'hypha facia': ['drain luck','drain agility','drain fatigue','detect enchantment'],
'kagouti hide': ['drain fatigue','fortify speed','resist common disease','night eye'],
'kresh fiber': ['restore luck', 'fortify personality', 'drain magicka', 'drain speed'],
'kwama cuttle': ['resist poison','drain fatigue','water walking','water breathing'],
'large kwama egg': ['restore fatigue','paralyze','frost shield','fortify health'],
'luminous russula': ['water breathing','drain fatigue','poison'],
'marshmerrow': ['restore health','detect enchantment','drain willpower','drain fatigue'],
'moon sugar': ['fortify speed','dispel','drain endurance','drain luck'],
'muck': ['drain intelligence','detect key','drain personality','cure common disease'],
'netch leather': ['fortify endurance','fortify intelligence','drain personality','cure paralyzation'],
'pearl': ['drain agility','dispel','water breathing','resist common disease'],
'racer plumes': ['drain willpower','levitate'],
'rat meat': ['drain magicka','paralyze','cure poison','resist poison'],
'raw ebony': ['drain agility','cure poison','frost shield','restore speed'],
'raw glass': ['drain intelligence','drain strength','drain speed','fire shield'],
'red lichen': ['drain speed','light','cure common disease','drain magicka'],
'resin': ['restore health','restore speed','burden','resist common disease'],
'roobrush': ['drain willpower','fortify agility','drain health','cure poison'],
'ruby': ['drain health','feather','restore intelligence','drain agility'],
'saltrice': ['restore fatigue','fortify magicka','drain strength','restore health'],
'scales': ['drain personality','water walking','restore endurance','swift swim'],
'scamp skin': ['drain magicka','cure paralyzation','restore personality','restore strength'],
'scathecraw': ['drain strength','cure poison','drain health','restore willpower'],
'scrap metal': ['drain health','lightning shield','resist shock','restore intelligence'],
'scrib jelly': ['fortify willpower','cure poison','cure blight disease','restore willpower'],
'scrib jerky': ['restore fatigue','fortify fatigue','burden','swift swim'],
'scuttle': ['restore fatigue','fortify fatigue','feather','telekinesis'],
'shalk resin': ['drain fatigue','fortify health','drain personality','fortify speed'],
'sload soap': ['drain personality','fortify agility','fire shield','restore agility'],
'small kwama egg': ['restore fatigue'],
'spore pod': ['drain strength','drain fatigue','detect key','paralyze'],
'stoneflower petals': ['restore strength','fortify magicka','drain luck','fortify personality'],
'trama root': ['restore willpower','levitate','drain magicka','drain speed'],
'vampire dust': ['fortify health','fortify strength','spell absorption','vampirism'],
'violet coprinus': ['water walking','drain fatigue','poison'],
'void salts': ['restore magicka','spell absorption','paralyze','drain endurance'],
'wickwheat': ['restore health','fortify willpower','paralyze','damage intelligence'],
'willow anther': ['drain personality','frost shield','cure common disease','cure paralyzation']
}

listOfEffects = ['blind','burden','night eye','cure blight disease','cure common disease','paralyze','cure paralyzation','cure poison','poison','damage fatigue','damage health','drain speed','resist common disease',
                'damage intelligence','damage magicka','detect animal','drain strength','detect enchantment','resist frost','detect key','dispel','resist magicka','drain alteration','drain agility','feather','fire shield',
                'restore agility','drain endurance','restore endurance','restore fatigue','drain fatigue','fortify attack','fortify endurance','fortify fatigue','restore health','fortify health','fortify intelligence',
                'fortify luck','fortify magicka','restore luck','drain health','fortify maximum magicka','fortify personality','fortify speed','restore personality','restore speed','fortify strength','restore strength',
                'drain intelligence','restore willpower','fortify willpower','spell absorption','drain luck','frost shield','telekinesis','invisibility','vampirism','water breathing','levitate','water walking','light',
                'weakness to fire','weakness to poison','drain magicka','drain personality','recall','reflect','resist fire','drain willpower','resist paralysis','resist poison','resist shock','fortify agility',
                'restore intelligence','restore magicka','frost damage','swift swim','lightning shield']

restock_merchants = {'ajira': {'location': 'balmora, guild of mages',
  'ingredients': ['black anther',
   'comberry',
   'crab meat',
   'heather',
   'hound meat',
   'kwama cuttle',
   'scales',
   'small kwama egg',
   'willow anther']},
 'anarenen': {'location': "ald'ruhn, guild of mages",
  'ingredients': ['bloat',
   'bonemeal',
   'comberry',
   'crab meat',
   'diamond',
   'fire salts',
   'heather',
   'vampire dust']},
 'andil': {'location': 'tel vos, services tower',
  'ingredients': ['black anther',
   'gold kanet',
   'kresh fiber',
   'marshmerrow',
   'scathecraw',
   'shalk resin',
   'stoneflower petals']},
 'andilu drothan': {'location': 'vivec foreign quarter, andilu drothan: alchemist',
  'ingredients': ['comberry',
   'gold kanet',
   'heather',
   'muck',
   'scrap metal',
   'sload soap',
   'trama root']},
 'anis seloth': {'location': 'sadrith mora, anis seloth: alchemist',
  'ingredients': ['alit hide',
   'bloat',
   'bonemeal',
   'coda flower',
   'daedra skin',
   "daedra's heart",
   'diamond',
   'fire salts',
   'frost salts',
   'ghoul heart',
   'hackle-lo leaf',
   'heather',
   'hypha facia',
   'kwama cuttle',
   'luminous russula',
   'muck',
   'pearl',
   'ruby',
   'scales',
   'scrap metal',
   'sload soap',
   'trama root',
   'vampire dust',
   'violet coprinus',
   'wickwheat',
   'willow anther']},
 'arnand liric': {'location': 'buckmoth legion fort, interior',
  'ingredients': ['corprus weepings',
   'gravedust',
   'hound meat',
   'netch leather',
   'scamp skin',
   'scrib jelly']},
 'arrille': {'location': "seyda neen, arrille's tradehouse",
  'ingredients': ['corkbulb root', 'scrib jerky', 'shalk resin']},
 'aunius autrus': {'location': 'wolverine hall, imperial shrine',
  'ingredients': ['ash yam',
   'bloat',
   'gravedust',
   'guar hide',
   'netch leather',
   'scamp skin',
   'scrib jerky']},
 'aurane frernis': {'location': 'vivec, foreign quarter, aurane frernis: apothecary',
  'ingredients': ['black anther',
   'coda flower',
   'corprus weepings',
   'green lichen',
   'hypha facia',
   'red lichen',
   'resin',
   'shalk resin']},
 'bildren areleth': {'location': 'tel aruhn, bildren areleth: apothecary',
  'ingredients': ['bittergreen petals',
   'ectoplasm',
   'heather',
   'kagouti hide',
   'kresh fiber',
   'resin',
   'stoneflower petals']},
 'brarayni sarys': {'location': 'tel aruhn, tower entry',
  'ingredients': ['black anther',
   'coda flower',
   'daedra skin',
   'diamond',
   'ghoul heart',
   'heather',
   'muck',
   'racer plumes',
   'sload soap',
   'spore pod',
   'vampire dust']},
 'chaplain ogrul': {'location': 'gnisis, fort darius',
  'ingredients': ['ash yam',
   'crab meat',
   'marshmerrow',
   'rat meat',
   'saltrice',
   'wickwheat']},
 'cienne sintieve': {'location': "ald'ruhn, cienne sintieve: alchemist",
  'ingredients': ['ampoule pod',
   'coda flower',
   'frost salts',
   'hound meat',
   'kwama cuttle',
   'racer plumes',
   'scrap metal',
   'small kwama egg',
   'spore pod',
   'violet coprinus',
   'void salts']},
 'cocistian quaspus': {'location': 'buckmoth legion fort',
  'ingredients': ['bittergreen petals',
   'emerald',
   'fire petal',
   'kresh fiber',
   'rat meat',
   'scathecraw',
   'stoneflower petals']},
 'craetia jullalian': {'location': 'vivec foreign quarter, guild of mages',
  'ingredients': ['alit hide',
   'ampoule pod',
   'bloat',
   'corkbulb root',
   'crab meat',
   "daedra's heart",
   'diamond',
   'emerald',
   'fire salts',
   'frost salts',
   'ghoul heart',
   'pearl',
   'racer plumes',
   'ruby']},
 'danoso andrano': {'location': "ald'ruhn, temple",
  'ingredients': ["bungler's bane",
   'coda flower',
   'dreugh wax',
   'ectoplasm',
   'hypha facia',
   'marshmerrow',
   'pearl',
   'roobrush',
   'spore pod',
   'wickwheat']},
 'daynali dren': {'location': 'tel mora, lower tower',
  'ingredients': ['alit hide',
   'black anther',
   'bloat',
   'crab meat',
   'diamond',
   'frost salts',
   'gold kanet',
   'hackle-lo leaf',
   'hound meat',
   'racer plumes',
   'ruby',
   'scales',
   'scrap metal',
   'trama root',
   'willow anther']},
 'dralval andrano': {'location': 'balmora, temple',
  'ingredients': ['black lichen',
   "bungler's bane",
   'green lichen',
   'hypha facia',
   'kagouti hide',
   'marshmerrow',
   'red lichen',
   'scathecraw',
   'wickwheat']},
 'dulian': {'location': 'buckmoth legion fort, interior',
  'ingredients': ['ash yam',
   'kwama cuttle',
   'muck',
   'resin',
   'scrib jerky',
   'trama root',
   'willow anther']},
 'eldrilu dalen': {'location': 'vos, vos chapel',
  'ingredients': ['ash salts',
   'ash yam',
   'corkbulb root',
   'fire salts',
   'guar hide',
   'netch leather',
   'saltrice',
   'scrib jelly',
   'scrib jerky']},
 'ernand thierry': {'location': 'caldera, guild of mages',
  'ingredients': ['alit hide',
   'ampoule pod',
   'coda flower',
   'corkbulb root',
   'luminous russula',
   'spore pod',
   'violet coprinus']},
 'felara andrethi': {'location': 'tel aruhn, tower living quarters',
  'ingredients': ['chokeweed',
   'comberry',
   'marshmerrow',
   'rat meat',
   'saltrice',
   'scamp skin',
   'scuttle',
   'small kwama egg']},
 'folvys andalor': {'location': "ald'ruhn temple",
  'ingredients': ['ash salts',
   'corprus weepings',
   'emerald',
   'guar hide',
   'rat meat',
   'scamp skin',
   'scrib jelly',
   'scrib jerky',
   'scuttle']},
 'galsa andranotr': {'location': 'mournhold temple: infirmary',
  'ingredients': ['horn lily bulb',
   'nirthfly stalks',
   'scrib jerky',
   'sweetpulp']},
 'galuro belan': {'location': 'vivec, telvanni apothecary',
  'ingredients': ['ectoplasm',
   'fire petal',
   'kagouti hide',
   'kresh fiber',
   'scathecraw',
   'stoneflower petals']},
 'ganalyn saram': {'location': 'vivec, hlaalu alchemist',
  'ingredients': ["bungler's bane",
   'corkbulb root',
   'hound meat',
   'kwama cuttle',
   'scales',
   'spore pod',
   'willow anther']},
 'garas seloth': {'location': 'vivec, telvanni alchemist',
  'ingredients': ['bonemeal',
   'daedra skin',
   'hackle-lo leaf',
   'pearl',
   'racer plumes',
   'void salts',
   'wickwheat']},
 'gils drelas': {'location': "tel branora, upper tower: therana's chamber",
  'ingredients': ["daedra's heart",
   'fire salts',
   'frost salts',
   'gold kanet',
   'hackle-lo leaf',
   'pearl',
   'ruby',
   'scales',
   'scrap metal',
   'trama root',
   'void salts',
   'willow anther']},
 'guls llervu': {'location': "ald'ruhn, guls llervu's house",
  'ingredients': ['corkbulb root',
   'kagouti hide',
   'resin',
   'saltrice',
   'scathecraw',
   'scuttle']},
 'irna maryon': {'location': 'tel aruhn, tower entry',
  'ingredients': ['black lichen',
   'emerald',
   'fire petal',
   'green lichen',
   'kwama cuttle',
   'red lichen',
   'roobrush',
   'scathecraw',
   'wickwheat']},
 "j'rasha": {'location': "vivec, foreign quarter, j'rasha: healer",
  'ingredients': ['ash yam',
   'chokeweed',
   'marshmerrow',
   'saltrice',
   'scamp skin',
   'scuttle',
   'small kwama egg']},
 'jolda': {'location': 'tel mora, jolda: apothecary',
  'ingredients': ['ampoule pod',
   'black lichen',
   "bungler's bane",
   'dreugh wax',
   'hypha facia',
   'luminous russula',
   'pearl',
   'resin',
   'violet coprinus',
   'void salts']},
 'llarara omayn': {'location': 'balmora, temple',
  'ingredients': ['corkbulb root',
   'ectoplasm',
   'hackle-lo leaf',
   'saltrice',
   'scrib jerky',
   'shalk resin',
   'wickwheat']},
 'llathyno hlaalu': {'location': 'balmora, temple',
  'ingredients': ['gravedust',
   'kresh fiber',
   'muck',
   'resin',
   'scrib jelly',
   'scuttle',
   'stoneflower petals',
   'trama root',
   'willow anther']},
 'lloros sarano': {'location': "ald'ruhn, temple",
  'ingredients': ['ghoul heart', 'gravedust', 'red lichen', 'shalk resin']},
 'mehra drora': {'location': 'gnisis, temple',
  'ingredients': ['bloat',
   'dreugh wax',
   'fire petal',
   'ghoul heart',
   'hackle-lo leaf',
   'netch leather',
   'stoneflower petals']},
 'milar maryon': {'location': 'tel vos, services tower',
  'ingredients': ['ash yam',
   'bonemeal',
   'comberry',
   'crab meat',
   'gravedust',
   'marshmerrow',
   'rat meat',
   'wickwheat']},
 'nalcarya of white haven': {'location': 'balmora, nalcarya of white haven: fine alchemist',
  'ingredients': ['alit hide',
   'black anther',
   'bloat',
   'daedra skin',
   "daedra's heart",
   'diamond',
   'fire salts',
   'frost salts',
   'kwama cuttle',
   'muck',
   'pearl',
   'racer plumes',
   'ruby',
   'scales',
   'scrap metal',
   'sload soap',
   'trama root',
   'vampire dust',
   'void salts']},
 'peragon': {'location': 'moonmoth legion fort, interior',
  'ingredients': ['coda flower',
   'gold kanet',
   'heather',
   'luminous russula',
   'pearl',
   'sload soap',
   'spore pod']},
 'pierlette rostorard': {'location': 'sadrith mora, pierlette rostorard: apothecary',
  'ingredients': ['black lichen',
   'dreugh wax',
   'ectoplasm',
   'fire petal',
   'kagouti hide',
   'kresh fiber',
   'red lichen',
   'resin',
   'roobrush',
   'scathecraw',
   'shalk resin',
   'stoneflower petals']},
 'relms gilvilo': {'location': 'vivec, redoran temple shrine',
  'ingredients': ['ash salts',
   'black lichen',
   'dreugh wax',
   'fire salts',
   'ghoul heart',
   'roobrush',
   'scrib jelly']},
 'salen ravel': {'location': 'maar gan, shrine',
  'ingredients': ['dreugh wax',
   'ectoplasm',
   'gravedust',
   'kagouti hide',
   'shalk resin']},
 'scelian plebo': {'location': 'wolverine hall, imperial shrine',
  'ingredients': ['ash salts',
   'bittergreen petals',
   'bonemeal',
   'chokeweed',
   'comberry',
   'corprus weepings',
   'emerald',
   'green lichen',
   'marshmerrow',
   'rat meat',
   'saltrice']},
 'sedris omalen': {'location': 'maar gan, outpost',
  'ingredients': ['alit hide',
   'black lichen',
   'corkbulb root',
   'hackle-lo leaf',
   'saltrice']},
 'somutis vunnis': {'location': 'moonmoth legion fort, interior',
  'ingredients': ['ash salts',
   'black lichen',
   'dreugh wax',
   'fire petal',
   'kresh fiber',
   'roobrush']},
 'telis salvani': {'location': 'balmora, temple',
  'ingredients': ['ash salts',
   'bittergreen petals',
   'chokeweed',
   'comberry',
   'green lichen',
   'netch leather',
   'rat meat']},
 'threvul serethi': {'location': 'sadrith mora, thervul [sic] serethi: healer',
  'ingredients': ['bittergreen petals',
   'corprus weepings',
   'hound meat',
   'netch leather',
   'scrib jelly',
   'scuttle',
   'small kwama egg',
   'wickwheat']},
 'tivam sadri': {'location': 'holamayan monastery',
  'ingredients': ['ash salts',
   'corkbulb root',
   'ectoplasm',
   'ghoul heart',
   'gravedust',
   'hackle-lo leaf',
   'muck',
   'saltrice',
   'scrib jerky']},
 'tusamircil': {'location': 'wolverine hall, mages guild',
  'ingredients': ['ampoule pod',
   "bungler's bane",
   'corkbulb root',
   'crab meat',
   'hound meat',
   'kwama cuttle',
   'racer plumes',
   'small kwama egg',
   'spore pod',
   'trama root']},
 'ulumpha gra-sharob': {'location': 'gnisis, fort darius',
  'ingredients': ['bonemeal', 'frost salts', 'hound meat', 'small kwama egg']},
 'vaval selas': {'location': 'vivec, st. olms temple',
  'ingredients': ['bittergreen petals',
   'chokeweed',
   'gravedust',
   'rat meat',
   'saltrice',
   'scrib jelly',
   'small kwama egg']},
 'ygfa': {'location': 'pelagiad, fort pelagiad',
  'ingredients': ['ash yam',
   'bittergreen petals',
   'chokeweed',
   'guar hide',
   'marshmerrow']},
 'zanmulk sammalamus': {'location': 'gnisis, temple',
  'ingredients': ['ash yam',
   'bittergreen petals',
   'hound meat',
   'rat meat',
   'small kwama egg']}}